;; -*- coding: utf-8 -*-

;; Xah Lee
;; 2010-11-16

;; a abbrev set for emacs-list-mode.

;; Place this file in the dir 〔~/.emacs.d/〕.
;; Then, restart emacs.
;; Then, you'll have these abbrevations when your are in emac-lisp-mode.
;; See also: 
;; 〈Using Emacs's Abbrev Mode for Abbreviation〉 http://xahlee.org/emacs/emacs_abbrev_mode.html
;; 〈Yasnippet Templates for Emacs Lisp Mode〉  http://xahlee.org/emacs/elisp_idiom_templates.html

(define-abbrev-table 'lisp-mode-abbrev-table '(

 ;; single letter name has abbrev start with 8
 ("8d" "defun" nil 0)
 ("8i" "insert" nil 0)
 ("8l" "let" nil 0)
 ("8m" "message" nil 0)
 ("8p" "point" nil 0)
 ("8s" "setq" nil 0)
 ("8v" "vector" nil 0)
 ("8w" "when" nil 0)

 ("ah" "add-hook" nil 0)
 ("bc" "backward-char" nil 0)
 ("bfn" "buffer-file-name" nil 0)
 ("bmp" "buffer-modified-p" nil 0)
 ("bol" "beginning-of-line" nil 0)
 ("botap" "bounds-of-thing-at-point" nil 0)
 ("bs" "buffer-substring" nil 0)
 ("bsnp" "buffer-substring-no-properties" nil 0)
 ("ca" "custom-autoload" nil 0)
 ("cb" "current-buffer" nil 0)
 ("cc" "condition-case" nil 0)
 ("cd" "copy-directory" nil 0)
 ("cdr" "cdr" nil 0)
 ("cf" "copy-file" nil 0)
 ("dc" "delete-char" nil 0)
 ("dd" "delete-directory" nil 0)
 ("df" "delete-file" nil 0)
 ("dk" "define-key" nil 0)
 ("dr" "delete-region" nil 0)
 ("efn" "expand-file-name" nil 0)
 ("eol" "end-of-line" nil 0)
 ("fc" "forward-char" nil 0)
 ("ff" "find-file" nil 0)
 ("fl" "forward-line" nil 0)
 ("fnd" "file-name-directory" nil 0)
 ("fne" "file-name-extension" nil 0)
 ("fnn" "file-name-nondirectory" nil 0)
 ("fnse" "file-name-sans-extension" nil 0)
 ("frn" "file-relative-name" nil 0)
 ("gc" "goto-char" nil 0)
 ("gnb" "generate-new-buffer" nil 0)
 ("gsk" "global-set-key" nil 0)
 ("ifc" "insert-file-contents" nil 0)
 ("kb" "kill-buffer" nil 0)
 ("la" "looking-at" nil 0)
 ("lbp" "line-beginning-position" nil 0)
 ("lep" "line-end-position" nil 0)
 ("mb" "match-beginning" nil 0)
 ("md" "make-directory" nil 0)
 ("me" "match-end" nil 0)
 ("mlv" "make-local-variable" nil 0)
 ("ms" "match-string" nil 0)
 ("nts" "number-to-string" nil 0)
 ("pm" "point-min" nil 0)
 ("rap" "region-active-p" nil 0)
 ("rb" "region-beginning" nil 0)
 ("re" "region-end" nil 0)
 ("rf" "rename-file" nil 0)
 ("rq" "regexp-quote" nil 0)
 ("rr" "replace-regexp" nil 0)
 ("rris" "replace-regexp-in-string" nil 0)
 ("rsb" "re-search-backward" nil 0)
 ("rsf" "re-search-forward" nil 0)
 ("sb" "set-buffer" nil 0)
 ("sbr" "search-backward-regexp" nil 0)
 ("sc" "shell-command" nil 0)
 ("scb" "skip-chars-backward" nil 0)
 ("scf" "skip-chars-forward" nil 0)
 ("se" "save-excursion" nil 0)
 ("sf" "search-forward" nil 0)
 ("sfm" "set-file-modes" nil 0)
 ("sfr" "search-forward-regexp" nil 0)
 ("sm" "string-match" nil 0)
 ("ss" "split-string" nil 0)
 ("stn" "string-to-number" nil 0)
 ("str" "string" nil 0)
 ("tap" "thing-at-point" nil 0)
 ("wcb" "with-current-buffer" nil 0)
 ("wg" "widget-get" nil 0)
 ("yonp" "yes-or-no-p" nil 0)
 )
  )
