;; -*- coding: utf-8 -*-

;; Xah Lee
;; 2010-11-16

;; a abbrev set for emacs-list-mode.

;; Place this file in the dir 〔~/.emacs.d/〕.
;; put this in your emacs init: (load "init_abbrevs-lisp-mode")
;; Then, restart emacs.
;; Then, you'll have these abbrevations when your are in emac-lisp-mode.
;; See also: 
;; 〈Using Emacs's Abbrev Mode for Abbreviation〉 http://ergoemacs.org/emacs/emacs_abbrev_mode.html
;; 〈Yasnippet Templates for Emacs Lisp Mode〉  http://ergoemacs.org/emacs/elisp_idiom_templates.html

(define-abbrev-table 'lisp-mode-abbrev-table '(

 ;; single letter name has abbrev start with 8
 ("8d" "defun")
 ("8i" "insert")
 ("8l" "let")
 ("8m" "message")
 ("8p" "point")
 ("8s" "setq")
 ("8v" "vector")
 ("8w" "when")

 ("ah" "add-hook")
 ("bc" "backward-char")
 ("bfn" "buffer-file-name")
 ("bmp" "buffer-modified-p")
 ("bol" "beginning-of-line")
 ("botap" "bounds-of-thing-at-point")
 ("bs" "buffer-substring")
 ("bsnp" "buffer-substring-no-properties")
 ("ca" "custom-autoload")
 ("cb" "current-buffer")
 ("cc" "condition-case")
 ("cd" "copy-directory")
 ("cdr" "cdr")
 ("cf" "copy-file")
 ("dc" "delete-char")
 ("dd" "delete-directory")
 ("df" "delete-file")
 ("dk" "define-key")
 ("dr" "delete-region")
 ("efn" "expand-file-name")
 ("eol" "end-of-line")
 ("fc" "forward-char")
 ("ff" "find-file")
 ("fl" "forward-line")
 ("fnd" "file-name-directory")
 ("fne" "file-name-extension")
 ("fnn" "file-name-nondirectory")
 ("fnse" "file-name-sans-extension")
 ("frn" "file-relative-name")
 ("gc" "goto-char")
 ("gnb" "generate-new-buffer")
 ("gsk" "global-set-key")
 ("ifc" "insert-file-contents")
 ("kb" "kill-buffer")
 ("la" "looking-at")
 ("lbp" "line-beginning-position")
 ("lep" "line-end-position")
 ("mb" "match-beginning")
 ("md" "make-directory")
 ("me" "match-end")
 ("mlv" "make-local-variable")
 ("ms" "match-string")
 ("nts" "number-to-string")
 ("ntr" "narrow-to-region")
 ("pm" "point-max")
 ("rap" "region-active-p")
 ("rb" "region-beginning")
 ("re" "region-end")
 ("rf" "rename-file")
 ("rm" "replace-match")
 ("rq" "regexp-quote")
 ("rr" "replace-regexp")
 ("rris" "replace-regexp-in-string")
 ("rsb" "re-search-backward")
 ("rsf" "re-search-forward")
 ("sb" "set-buffer")
 ("sbr" "search-backward-regexp")
 ("sc" "shell-command")
 ("scb" "skip-chars-backward")
 ("scf" "skip-chars-forward")
 ("se" "save-excursion")
 ("sf" "search-forward")
 ("sfm" "set-file-modes")
 ("sfr" "search-forward-regexp")
 ("sm" "string-match")
 ("sr" "save-restriction")
 ("ss" "split-string")
 ("stn" "string-to-number")
 ("str" "string")
 ("tap" "thing-at-point")
 ("wcb" "with-current-buffer")
 ("wg" "widget-get")
 ("yonp" "yes-or-no-p")
 )
  )
